apiVersion: v1
kind: Service
metadata:
  name: resource-app-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: resource-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30200

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-app-deployment
  namespace: k8s-program
  labels:
    app: resource-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resource-app
  template:
    metadata:
      namespace: k8s-program
      labels:
        app: resource-app
    spec:
      containers:
        - name: resource-app
          image: resource-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SERVER_PORT
              value: '8080'
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://resource-db-service:5432/resource-db
            - name: SONGSERVICE_URL
              value: http://song-app-service:8080/songs

---

apiVersion: v1
kind: Service
metadata:
  name: resource-db-service
  namespace: k8s-program
spec:
  type: ClusterIP
  selector:
    app: resource-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resource-db-statefulset
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: resource-db
  serviceName: resource-db
  template:
    metadata:
      labels:
        app: resource-db
    spec:
      containers:
        - name: resource-db
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: resource-db
          volumeMounts:
            - name: resource-db-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: resource-db-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "hostpath"
        resources:
          requests:
            storage: 1Gi
