### Send a form with the text and file fields
POST http://localhost:8080/resources
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.mp3"

< ./src/test/resources/test.mp3
--WebAppBoundary--

###
GET http://localhost:8080/resources/1

###
DELETE http://localhost:8080/resources/1